### 넘파이(Numpy) : 배열(ndarray, n dimension array)
#### 리스트(list): Linked List 구조(불연속), 동작 속도가 느리다, comma로 요소 구별, 서로 다른 자료형 사용가능
#### 배열(ndarray) : 연속된 메모리 구조, 동작 속도가 빠르다, comma를 사용하지 않고 공백으로 요소를 구별, 오직 한 가지 타입만 갖을 수 있다

In [7]:
import numpy as np

# list
list1 = [0,1,2,3,4,5,'hello']
print(list1,type(list1))

# ndarray
a = np.array([0,1,2,3,4,5])
print(a,type(a))
print(a.dtype)

[0, 1, 2, 3, 4, 5, 'hello'] <class 'list'>
[0 1 2 3 4 5] <class 'numpy.ndarray'>
int32


In [10]:
# numpy 의 dtype 객체의 종류 : 대소문자 모두 사용 가능
np.sctypeDict.keys()

dict_keys(['?', 0, 'byte', 'b', 1, 'ubyte', 'B', 2, 'short', 'h', 3, 'ushort', 'H', 4, 'i', 5, 'uint', 'I', 6, 'intp', 'p', 9, 'uintp', 'P', 10, 'long', 'l', 7, 'ulong', 'L', 8, 'longlong', 'q', 'ulonglong', 'Q', 'half', 'e', 23, 'f', 11, 'double', 'd', 12, 'longdouble', 'g', 13, 'cfloat', 'F', 14, 'cdouble', 'D', 15, 'clongdouble', 'G', 16, 'O', 17, 'S', 18, 'unicode', 'U', 19, 'void', 'V', 20, 'M', 21, 'm', 22, 'b1', 'bool8', 'i8', 'int64', 'u8', 'uint64', 'f2', 'float16', 'f4', 'float32', 'f8', 'float64', 'c8', 'complex64', 'c16', 'complex128', 'object0', 'bytes0', 'str0', 'void0', 'M8', 'datetime64', 'm8', 'timedelta64', 'int32', 'i4', 'uint32', 'u4', 'int16', 'i2', 'uint16', 'u2', 'int8', 'i1', 'uint8', 'u1', 'complex_', 'single', 'csingle', 'singlecomplex', 'float_', 'intc', 'uintc', 'int_', 'longfloat', 'clongfloat', 'longcomplex', 'bool_', 'bytes_', 'string_', 'str_', 'unicode_', 'object_', 'int', 'float', 'complex', 'bool', 'object', 'str', 'bytes', 'a', 'int0', 'uint0'])

### 차원(Dimension,Rank) 과 Shape
#### * 차원(Dimension,Rank)  : 1,2,3차원,n차원, 첫 데이터까지의 대괄호의 갯수
#### * Shape : 차원의 요소의 수, 튜플 형식
####  1 차원 Shape : (x,) , 벡터(vector)
####  2 차원 Shape : (x,y), 행렬(matrix)
####  3 차원 Shape : (x,y,z) , (면,행,열) 
... 
####  n 차원 Shape : (x,y,z,....)

In [14]:
# 1차원 배열의 shape
a = np.arange(12)
print(a)
print(a.shape)   # (12,)
print(a.ndim)    # 1차원

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
1


In [17]:
# 2차원 배열의 Shape : 행(row,가로,수직,axis=0)과 열(column,세로,수평,axis=1) => 필수암기
m = np.array([[0,1,2],
              [0,1,2]])
print(m)
print(m.shape)   # (2,3)
print(m.ndim)    # 2차원

[[0 1 2]
 [0 1 2]]
(2, 3)
2


In [22]:
# 3 차원 배열의 Shape: (면,행,열)
m = np.array([[[0,1,2],
               [3,4,5]],
              [[0,1,2],
               [3,4,5]]])
print(m)
print(m.shape)  # (2,2,3)
print(m.ndim)   # 3차원

m = np.array([[[0, 1, 2]],
              [[3, 4, 5]],
              [[0, 1, 2]],
              [[3, 4, 5]]])
print(m,m.shape)

[[[0 1 2]
  [3 4 5]]

 [[0 1 2]
  [3 4 5]]]
(2, 2, 3)
3
[[[0 1 2]]

 [[3 4 5]]

 [[0 1 2]]

 [[3 4 5]]] (4, 1, 3)


In [28]:
# 4차원
m1 = np.arange(12).reshape(3,2,1,2)
print(m1)
print(m1.shape)

[[[[ 0  1]]

  [[ 2  3]]]


 [[[ 4  5]]

  [[ 6  7]]]


 [[[ 8  9]]

  [[10 11]]]]
(3, 2, 1, 2)


### 배열의 인덱싱과 슬라이싱

In [30]:
# 1차원 배열의 인덱싱과 슬라이싱 : list 와 동일한 방법
d = np.arange(12)
print(d,d.shape)

# indexing
print(d[0],d[1],d[2],d[-1],d[-2])

# slicing
print(d[2:8],d[:],d[:-1])
print(d[::2],d[::-1])

d[0] = 10   # list 처럼 요소 변경이 가능
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11] (12,)
0 1 2 11 10
[2 3 4 5 6 7] [ 0  1  2  3  4  5  6  7  8  9 10 11] [ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  2  4  6  8 10] [11 10  9  8  7  6  5  4  3  2  1  0]
[10  1  2  3  4  5  6  7  8  9 10 11]


In [48]:
# 2차원 배열의 인덱싱과 슬라이싱 
# data[행,열]
d = np.arange(12).reshape(3,4)
print(d,d.shape)  # (3, 4)

# indexing
print(d[0][0])  # 0
print(d[0,0])   # 0
print(d[2,1])   # 9



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)
0
0
9
