### OpenCV 기초

In [1]:
# ! pip install opencv-python
import cv2
import numpy as np
import time
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
cv2.__version__

'4.11.0'

### [1] 직선(Line) 그리기

In [3]:
# 직선(Line) 그리기
# 흰색 배경의 빈 이미지 생성
image = np.ones((500,500,3), dtype=np.uint8)  # 요소를 1로 초기화 해서 생성
image = image *255                         # 요소에 255를 곱함

# 직선 그리기 (시작점, 끝점, 색상, 두께)
cv2.line(image,(50,150),(450,150),(255,0,0),3)   # Color:Blue
cv2.line(image,(150,50),(150,450),(0,255,0),3)   # Color:Green
cv2.line(image,(50,50),(450,450),(0,0,255),3)    # Color:Red

cv2.imshow("Line Drawing",image)
cv2.waitKey(0)                    # 이후 예제 모두 'ESC' 키로 종료 가능
cv2.destroyAllWindows()

In [35]:
# 여러 개의 랜덤한 직선을 그리는 프로그램
import random

# 캔버스 크기 설정
width, height = 500, 500
image = np.ones((height, width, 3), dtype=np.uint8) * 255  # 흰색 배경

# 랜덤한 직선을 여러 개 그리기
num_lines = 10  # 그릴 직선 개수

for _ in range(num_lines):
    # 랜덤한 시작점과 끝점 생성
    x1, y1 = random.randint(0,width), random.randint(0,height)
    x2, y2 = random.randint(0,width), random.randint(0,height)

    # 랜덤한 색상 생성 (B, G, R)
    color = (random.randint(0,255),random.randint(0,255),random.randint(0,255))

    # 랜덤한 두께 설정
    thickness = random.randint(1,5)

    # 직선 그리기
    cv2.line(image, (x1,y1), (x2,y2), color, thickness)

# 결과 출력
cv2.imshow("Random Lines", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

### [2] 사각형(Rectangle) 그리기

In [44]:
# 흰색 배경의 빈 이미지 생성
image = np.ones((500,500,3), dtype=np.uint8) *255

# 사각형 그리기 (시작점, 끝점, 색상, 두께)
cv2.rectangle(image, (100, 100), (200,200), (255,0,0), 3)

# 결과 출력
cv2.imshow("Rectangle Drawing", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [50]:
import random

# 캔버스 크기 설정
width, height = 500, 500
image = np.ones((height, width, 3), dtype=np.uint8) * 255  # 흰색 배경

# 랜덤한 사각형 여러 개 그리기
num_rectangles = 10  # 그릴 사각형 개수

for _ in range(num_rectangles):
    # 랜덤한 좌표 생성 (왼쪽 상단과 오른쪽 하단)
    x1, y1 = random.randint(0,width - 50), random.randint(0,height - 50)
    x2, y2 = random.randint(x1 + 20, width), random.randint(y1 + 20,height)

    # 랜덤한 색상 생성 (B, G, R)
    color = (random.randint(0,255),random.randint(0,255),random.randint(0,255))

    # 랜덤한 두께 설정
    thickness = random.choice([1,2,3,-1])    # -1이면 채운 사각형

    # 사각형 그리기 (시작점, 끝점, 색상, 두께)
    cv2.rectangle(image, (x1, y1), (x2, y2), color, thickness)    

# 결과 출력
cv2.imshow("Random Rectangles", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [53]:
# 직선과 사각형의 교차점 그리기
img = np.zeros(shape=(512,512,3), dtype=np.uint8) + 255

x1, x2 = 100, 400
y1, y2 = 100, 400
cv2.rectangle(img, (x1, y1), (x2, y2), (0, 0, 255))

pt1 = 120, 50
pt2 = 300, 500
cv2.line(img, pt1, pt2, (255,0,0), 2)

imgRect = (x1, y1, x2-x1, y2-y1)
retval, rpt1, rpt2 = cv2.clipLine(imgRect, pt1, pt2)
print(rpt1,rpt2)
if retval:
    cv2.circle(img, rpt1, radius=5, color=(0, 255, 0), thickness=-1)
    cv2.circle(img, rpt2, radius=5, color=(0, 255, 0), thickness=-1)

cv2.imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()

(140, 100) (260, 399)


### [3] 원(Circle) 및 타원(Ellipse) 그리기

In [68]:
# 흰색 배경의 빈 이미지 생성
image = np.ones((500,500,3), dtype=np.uint8) *255

# 원 그리기 (중심 좌표, 반지름, 색상, 두께)
cv2.circle(image, (250, 250), 100, (0,255,0), 3)

# 결과 출력
cv2.imshow("Circle Drawing", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [90]:
# 원 내부 채우기
img = np.zeros(shape=(512,512,3), dtype=np.uint8) + 255
cy = img.shape[0]//2
cx = img.shape[1]//2

for r in range(200, 0, -100):
    cv2.circle(img, (cx, cy), r, color=(255, 0, 0))

cv2.circle(img, (cx, cy), radius=50, color=(0,0,255), thickness=-1)   # thickness : Negative values, like #FILLED,

cv2.imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()

In [93]:
# 타원 그리기
# cv2.ellipse(image, center, axes, angle, startAngle, endAngle, color, thickness)
# center: 타원의 중심 좌표 (이미지 중앙 (250, 250))
# axes: 타원의 가로 반지름과 세로 반지름 (150, 100)
# angle: 타원의 회전 각도 (0도)
# startAngle: 시작 각도 (0도)
# endAngle: 끝 각도 (360도 → 완전한 타원)
# color: 타원의 색상 (파란색 (255, 0, 0))
# thickness: 테두리 두께 (3픽셀, -1을 사용하면 채워진 타원)

# 흰색 배경의 빈 이미지 생성
image = np.ones((500,500,3), dtype=np.uint8) *255

# 원 그리기 (중심 좌표, 크기, 회전 각도, 시작 각도, 끝 각도, 색상, 두께)
cv2.ellipse(image, (250, 250), (150,100),0,0,360,(255,0,0), 3)

# 결과 출력
cv2.imshow("Ellipse Drawing", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [94]:
# 다양한 타원 그리기
img = np.zeros(shape=(512,512,3), dtype=np.uint8) + 255
ptCenter = img.shape[1]//2, img.shape[0]//2
size = 200,100

cv2.ellipse(img, ptCenter, size, 0, 0, 360, (255, 0, 0))
cv2.ellipse(img, ptCenter, size, 45, 0, 360, (0, 0, 255))

box = (ptCenter, size, 0)
cv2.ellipse(img, box,  (255, 0, 0), 5)

box = (ptCenter, size, 45)
cv2.ellipse(img, box,  (0, 0, 255), 5)

cv2.imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()

### [4] 다각형(Polygon) 그리기

In [113]:
# 오각형 그리기
# 흰색 배경의 빈 이미지 생성
image = np.ones((500, 500, 3), dtype=np.uint8) * 255

# 오각형의 꼭지점 좌표 정의
points = np.array([[250, 100], [150, 200], [175, 350], 
                   [325, 350], [350, 200]], np.int32)

# 육각형의 꼭짓점 좌표 정의
# points = np.array([[150, 250], [200, 150], [300, 150], 
#                    [350, 250], [300, 350], [200, 350]], np.int32)

print(points.shape)                 # (5,2)
points = points.reshape((-1,1,2))   # (5,1,2),  OpenCV에 맞게 변환
print(points)

# 다각형 그리기 (닫힌 도형)
cv2.polylines(image,[points],isClosed=True,color=(255,0,0),thickness=3)

# 결과 출력
cv2.imshow("Polygon Drawing", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

(6, 2)
[[[150 250]]

 [[200 150]]

 [[300 150]]

 [[350 250]]

 [[300 350]]

 [[200 350]]]


In [108]:
# 두 개의 다각형(삼각형과 사각형) 그리기
img = np.zeros(shape=(512,512,3), dtype=np.uint8) + 255

pts1 = np.array([[100, 100], [200, 100], [200, 200], [100, 200]])
pts2 = np.array([[300, 200], [400, 100], [400, 200]])

cv2.polylines(img, [pts1, pts2], isClosed=True, color=(255, 0, 0))

cv2.imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()

In [112]:
# 회전 사각형 그리기
img = np.zeros(shape=(512,512,3), dtype=np.uint8) + 255

x, y = 256, 256
size = 200

for angle in range(0, 90, 10):
    rect = ((256, 256), (size, size), angle)
    box = cv2.boxPoints(rect).astype(np.int32)
    print(box)
    r = np.random.randint(256)
    g = np.random.randint(256)
    b = np.random.randint(256)   
    cv2.polylines(img, [box], True, (b, g, r), 2)
    
cv2.imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()

[[156 356]
 [156 156]
 [356 156]
 [356 356]]
[[140 337]
 [174 140]
 [371 174]
 [337 371]]
[[127 315]
 [196 127]
 [384 196]
 [315 384]]
[[119 292]
 [219 119]
 [392 219]
 [292 392]]
[[115 268]
 [243 115]
 [396 243]
 [268 396]]
[[115 243]
 [268 115]
 [396 268]
 [243 396]]
[[119 219]
 [292 119]
 [392 292]
 [219 392]]
[[127 196]
 [315 127]
 [384 315]
 [196 384]]
[[140 174]
 [337 140]
 [371 337]
 [174 371]]


In [119]:
# 다각형 채우기

img = np.zeros(shape=(512,512,3), dtype=np.uint8) + 255

pts1 = np.array([[100, 100], [200, 100], [200, 200], [100, 200]])
pts2 = np.array([[300, 200], [400, 100], [400, 200]])

# 한 개의 다각형 채우기
# cv2.fillConvexPoly(img, pts1, color=(255, 0, 0))

# 여러 개의 다각형 채우기
# cv2.fillPoly(img, [pts2], color=(0, 0, 255))   # 1개
cv2.fillPoly(img, [pts1, pts2], color=(0, 0, 255)) # 2개  

cv2.imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()

### [5] 문자열(Text) 출력

In [125]:
# 문자열 출력

# 흰색 배경의 빈 이미지 생성
image = np.ones((500, 500, 3), dtype=np.uint8) * 255

# 텍스트 추가
cv2.putText(image, "Hello, OpenCV!",(50,250),
            cv2.FONT_HERSHEY_SIMPLEX,1,(0,0,255),2,cv2.LINE_AA)  # Anti-Aliased : 텍스트의 외곽선을 부드럽게 그리는 방법

# 결과 출력
cv2.imshow("Text Example", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [127]:
# 타이핑 효과가 있는 텍스트 출력
import time

# 흰색 배경 이미지 생성
image = np.ones((500, 500, 3), dtype=np.uint8) * 255

# 출력할 텍스트
text = "Hello, OpenCV!"

# 텍스트 속성 설정
font = cv2.FONT_HERSHEY_SIMPLEX
font_scale = 1
thickness = 2
color = (0, 0, 255)  # 빨간색 (BGR)
start_x, start_y = 50, 250  # 시작 위치

# 한 글자씩 출력하는 애니메이션 효과
for i in range(len(text) + 1):
    temp_image = image.copy()  # 원본 이미지 유지
    cv2.putText(temp_image, text[:i], (start_x, start_y), font, font_scale, color, thickness, cv2.LINE_AA)
    cv2.imshow("Typing Effect", temp_image)
    cv2.waitKey(200)  # 200ms 대기 (입력 속도 조절)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [2]:
# 문자열에 사각형 씌우기
img = np.zeros(shape=(512,512,3), dtype=np.uint8) + 255
text = 'OpenCV Programming'
org = (50,100)
font = cv2.FONT_HERSHEY_SIMPLEX
cv2.putText(img,text, org, font, 1, (255,0,0), 2)

size, baseLine = cv2.getTextSize(text,font,1,2)
print('size:',size)
print('baseLine:',baseLine)

cv2.rectangle(img,org,(org[0]+size[0], org[1]-size[1]), (0, 0, 255))
cv2.circle(img, org, 3, (0, 255,0), 2)

cv2.imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()

size: (345, 22)
baseLine: 10


### [6] 키보드 이벤트 처리

In [24]:
# 키보드 이벤트 감지 및 처리


# 흰색 배경 이미지 생성
image = np.ones((500, 500, 3), dtype=np.uint8) * 255

cv2.imshow("Keyboard Event", image)

# cv2.waitKey(delay=0)
# delay	기다릴 시간(밀리초 단위, ms)
# 예: 1000이면 1초 동안 키 입력을 기다림
# 0	 : 무한정 기다림 (사용자가 키를 누를 때까지 창이 유지됨)
# >0 : 해당 시간만큼 기다렸다가 자동으로 다음 코드 실행됨
while True:
    key = cv2.waitKey(0) & 0xFF   #  키 입력 대기
    # print(key)
    # 'q' 키를 누르면 종료
    if key == ord('q'):
        print('프로그램 종료')
        break

    # 's' 키를 누르면 화면에 텍스트 출력
    elif key == ord('s'):
        cv2.putText(image, "Key 'S' Pressed!", (100, 250), 
                    cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 255), 2, cv2.LINE_AA)
        cv2.imshow("Keyboard Event", image)
        print("S 키가 눌렸습니다.")
        
cv2.destroyAllWindows()

S 키가 눌렸습니다.
S 키가 눌렸습니다.
S 키가 눌렸습니다.
S 키가 눌렸습니다.
S 키가 눌렸습니다.
S 키가 눌렸습니다.
프로그램 종료


In [22]:
# 키보드로 출력 제어

width, height = 512, 512
x, y, R = 256, 256, 50
direction = 0 # right

while True:   
    key = cv2.waitKeyEx(30)      
    if key == 0x1B:       # 'ESC' : 프로그램 종료
        print("프로그램 종료")
        break;
    
# 방향키 방향전환 
    elif key == 0x270000: # right
        direction = 0
    elif key == 0x280000: # down
        direction = 1
    elif key == 0x250000: # left
        direction = 2
    elif key == 0x260000: # up
        direction = 3
        
# 방향으로 이동 
    if direction == 0:     # right
        x += 10
    elif direction == 1:   # down
        y += 10
    elif direction == 2:   # left
        x -= 10
    else: # 3, up
        y -= 10

#   경계확인 
    if x < R:
        x = R
        direction = 0
    if x > width - R:
        x = width - R
        direction = 2
    if y < R:
        y = R
        direction = 1
    if y > height - R:
        y = height - R
        direction = 3
        
# 지우고, 그리기        
    img = np.zeros((width, height,3), np.uint8) + 255 # 지우기
    cv2.circle(img, (x, y), R, (0, 0, 255), -1) 
    cv2.imshow('img', img)
    
cv2.destroyAllWindows()


프로그램 종료


In [ ]:
0x00FF